apiVersion: v1
kind: PersistentVolume
metadata:
  name: parallelstore-pv
spec:
  storageClassName: parallelstore-class
  capacity:
    storage: 12000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: parallelstore.csi.storage.gke.io
    volumeHandle: "thomashk-mig/locations/us-central1/instances/parallelstore1/default-pool/default-container"
    volumeAttributes:
      accessPoints: 10.113.134.4,10.113.134.3,10.113.134.2
      network: default
