apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parallelstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: parallelstore-pv
  resources:
    requests:
      storage: 12000Gi # Range from 12,000Gi to 100,000Gi, must be in multiples of 4,000 GiB
  storageClassName: parallelstore-class

